<?php

function drujax_theme() {
  return array(
    'html__drujax' => array(
      'variables' => array('content' => NULL, 'messages' => NULL),
      'template' => 'html--drujax',
    ),
    'page__drujax' => array(
      'variables' => array('content'=>NULL, 'messages' => NULL),
      'template' => 'page--drujax'
    )
  );
}

function drujax_preprocess_html(&$vars) {
  $vars["ajax"] = (isset($_GET['ajax']) && $_GET['ajax'] == true ); 
  $vars["drujax_vars"] = drujax_var();
  if($vars["ajax"]){
    $vars["theme_hook_suggestions"]= array("html__drujax");
  }
  $theme_path = drupal_get_path('theme', 'drujax');
  $vars["theme_path"] = $theme_path;
}


function drujax_var($var_name= NULL, $new_val = NULL) {
  $vars = &drupal_static(__FUNCTION__, array());

  // If a new value has been passed
  if ($var_name && $new_val) {
    $vars[$var_name] = $new_val;
  }

  return $vars;
}

function drujax_preprocess_page(&$vars) {
  $vars["ajax"] = (isset($_GET['ajax']) && $_GET['ajax'] == true );
  if($vars["ajax"]){
    $vars["theme_hook_suggestions"][] = "page__drujax";
  }
  $theme_path = drupal_get_path('theme', 'drujax');
  $vars["theme_path"] = $theme_path;
  
  drupal_add_js(drupal_get_path('module', 'drujax') . '/js/vendor/jquery.address-1.5.min.js');
  drupal_add_js(drupal_get_path('module', 'drujax') . '/js/drujax.js');
}

function drujax_process_page(&$vars){
  /*$vars["ajax"] = (isset($_GET['ajax']) && $_GET['ajax'] == true ); 
  $vars["content"] = "";
  if(!$vars["ajax"]){
    $vars["content"] = drujax_render('page--drujax.tpl.php',$vars,"main");
  }*/
}

function drujax_render($template_file,$variables){
  extract($variables, EXTR_SKIP); // Extract the variables to a local namespace
  ob_start(); // Start output buffering
  
  global $theme;
  $theme_path = drupal_get_path('theme', $theme);
  $module_path = drupal_get_path('module', "drujax");
  
  $theme_file = "./$theme_path/templates/$template_file";
  $module_file = "./$module_path/$template_file";
  if(is_file($theme_file)){
    include $theme_file;
  }else{
    include $module_file;
  }
  
   // Include the template file
  $contents = ob_get_contents(); // Get the contents of the buffer
  ob_end_clean(); // End buffering and discard
  return $contents; // Return the contents
}

